appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.3.6
appReplicas: 2
containerPort: 9555
containerEnvVars:
  - name: PORT
    value: "9555"
  - name: DISABLE_AUTH
    value: "true"
  - name: ENABLE_STACKDRIVER_EXPORTER
    value: "false"

serviceType: ClusterIP
servicePort: 9555
